# Generated by Django 3.0.8 on 2020-07-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='surface_elevation',
            field=models.DecimalField(decimal_places=10, default=1500.2, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='structures',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='structures',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
