# Generated by Django 3.0.8 on 2020-08-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20200806_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipes',
            name='downstreamInvert',
        ),
        migrations.AddField(
            model_name='pipes',
            name='discharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipes',
            name='downstream_invert',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipes',
            name='pipe_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipes',
            name='pipe_length',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipes',
            name='upstream_invert',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
