# Generated by Django 3.0.8 on 2020-08-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20200806_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='structures',
            old_name='databaseKey',
            new_name='structure_id',
        ),
        migrations.AddField(
            model_name='pipes',
            name='project_id',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='pipes',
            name='system',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='structures',
            name='project_id',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
