# Generated by Django 3.0.8 on 2020-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20200813_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipes',
            name='order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=12),
        ),
    ]
