# Generated by Django 3.0.8 on 2020-08-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20200815_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic_Structures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_type', models.CharField(max_length=20)),
                ('drop_across_bottom', models.DecimalField(decimal_places=2, max_digits=19)),
                ('maximum_depth', models.DecimalField(decimal_places=2, max_digits=19)),
                ('18_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('24_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('30_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('36_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('\t42_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('48_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('54_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('60_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('72_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
                ('78_inch_minimum_depth', models.DecimalField(decimal_places=2, default='999', max_digits=15, null=True)),
            ],
        ),
    ]
