# Generated by Django 3.0.8 on 2020-08-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_generic_structures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_structures',
            name='\t42_inch_minimum_depth',
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='42_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='18_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='24_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='30_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='36_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='48_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='54_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='60_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='72_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='generic_structures',
            name='78_inch_minimum_depth',
            field=models.DecimalField(decimal_places=2, default='Nan', max_digits=15, null=True),
        ),
    ]
