# Generated by Django 3.0.8 on 2020-09-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20200830_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic_structures',
            name='18_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='24_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='30_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='36_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='42_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='48_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='54_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='60_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='72_inch_minimum_depth',
        ),
        migrations.RemoveField(
            model_name='generic_structures',
            name='78_inch_minimum_depth',
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_18_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_24_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_30_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_36_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_42_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_48_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_54_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_60_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_72_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_78_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
