# Generated by Django 3.0.8 on 2020-09-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20200903_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipes',
            name='design_downstream_invert',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pipes',
            name='design_upstream_invert',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
