# Generated by Django 3.1.1 on 2020-10-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20200919_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_12_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='generic_structures',
            name='minimum_depth_15_inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
